"""Tests for the human-facing claim reference.

The reference is generated by a PostgreSQL sequence in a column default, so these
tests pin the format, the schema wiring, and the database-level guarantees that
make concurrent inserts safe.
"""

from claims_service.models.claim import (
    CLAIM_REFERENCE_DIGITS,
    CLAIM_REFERENCE_PREFIX,
    CLAIM_REFERENCE_SEQUENCE,
    Claim,
    format_claim_reference,
)
from claims_service.schemas.claim import ClaimRead

import re

REFERENCE_PATTERN = re.compile(r"^CLM-\d{4}-\d{6}$")


def test_reference_format_is_prefixed_year_and_padded_sequence() -> None:
    assert format_claim_reference(2026, 42) == "CLM-2026-000042"
    assert REFERENCE_PATTERN.match(format_claim_reference(2026, 42))


def test_reference_padding_holds_at_boundaries() -> None:
    assert format_claim_reference(2026, 1) == "CLM-2026-000001"
    assert format_claim_reference(2026, 999_999) == "CLM-2026-999999"


def test_reference_beyond_padding_width_stays_parseable() -> None:
    """Overflowing the pad width must widen the number, never truncate it."""
    reference = format_claim_reference(2026, 1_000_000)
    assert reference == "CLM-2026-1000000"
    assert reference.split("-")[-1] == "1000000"


def test_reference_year_comes_from_the_claim_not_a_constant() -> None:
    assert format_claim_reference(2025, 7).startswith("CLM-2025-")
    assert format_claim_reference(2026, 7).startswith("CLM-2026-")


def test_claim_reference_column_is_unique_indexed_and_required() -> None:
    """Uniqueness is enforced by the database, not just by convention."""
    column = Claim.__table__.columns["claim_reference"]
    assert column.nullable is False
    assert column.unique is True
    assert column.index is True
    assert column.server_default is not None


def test_column_default_draws_from_the_shared_sequence() -> None:
    """Generating in the database is what makes concurrent inserts collision-free."""
    default_sql = str(Claim.__table__.columns["claim_reference"].server_default.arg)
    assert CLAIM_REFERENCE_SEQUENCE in default_sql
    assert "nextval" in default_sql
    assert f"lpad" in default_sql
    assert CLAIM_REFERENCE_PREFIX in default_sql


def test_reference_is_exposed_in_the_read_schema() -> None:
    """Operators can only quote the reference if the API actually returns it."""
    assert "claim_reference" in ClaimRead.model_fields
    assert ClaimRead.model_fields["claim_reference"].is_required()


def test_reference_column_fits_the_generated_format() -> None:
    longest = format_claim_reference(2026, 10 ** CLAIM_REFERENCE_DIGITS - 1)
    assert len(longest) <= Claim.__table__.columns["claim_reference"].type.length


def test_create_all_emits_sequence_before_the_table_that_uses_it():
    """The column default calls nextval(), so the sequence must exist first.

    Integration tests and scratch databases build the schema from the models
    rather than from Alembic. If the sequence is not attached to the metadata,
    create_all produces a table whose default references a missing sequence and
    every insert fails at runtime instead of at schema creation.
    """
    from sqlalchemy import create_mock_engine

    from claims_service.db.base import Base

    statements: list[str] = []
    engine = create_mock_engine(
        "postgresql://",
        lambda sql, *a, **k: statements.append(str(sql.compile(dialect=engine.dialect))),
    )
    Base.metadata.create_all(engine, checkfirst=False)

    sequence_at = next(
        i for i, s in enumerate(statements) if f"CREATE SEQUENCE {CLAIM_REFERENCE_SEQUENCE}" in s
    )
    table_at = next(i for i, s in enumerate(statements) if "CREATE TABLE claim " in s)

    assert sequence_at < table_at
