import { ApiClient, ApiError, type Claim, type Policy, type Workflow } from "./api";
import "./styles.css";

const client = new ApiClient({ token: import.meta.env.VITE_API_TOKEN });
const app = document.querySelector<HTMLDivElement>("#app")!;
let active = "overview";
let message = "";
let workflow: Workflow | null = null;

const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]!));
const badge = (value: string) => `<span class="badge badge-${esc(value).replaceAll("_", "-")}">${esc(value.replaceAll("_", " "))}</span>`;
function shell(content: string) {
  app.innerHTML = `<header class="topbar"><div class="brand"><span class="mark">OC</span><div><strong>Operations Console</strong><small>Claims orchestration</small></div></div><div class="top-actions"><span class="status-dot"></span> Services online <button id="menu" aria-label="Toggle navigation">☰</button></div></header><div class="layout"><nav aria-label="Main navigation"><button data-nav="overview" class="${active === "overview" ? "active" : ""}">▦ <span>Overview</span></button><button data-nav="workflows" class="${active === "workflows" ? "active" : ""}">↗ <span>Workflows</span></button><button data-nav="records" class="${active === "records" ? "active" : ""}">▤ <span>Records</span></button><button data-nav="reconciliation" class="${active === "reconciliation" ? "active" : ""}">◈ <span>Reconciliation</span></button></nav><main>${message ? `<div class="notice" role="status">${esc(message)}</div>` : ""}${content}</main></div>`;
  document.querySelectorAll<HTMLElement>("[data-nav]").forEach(b => b.onclick = () => { active = b.dataset.nav!; render(); });
}
function render() {
  if (active === "workflows") return shell(`<div class="page-head"><div><p class="eyebrow">Operations</p><h1>Submit workflow</h1><p class="muted">Start a claim workflow and monitor each saga step.</p></div></div><section class="card form-card"><form id="workflow-form"><div class="field-grid"><label>Policy ID<input name="policy_id" required placeholder="UUID"></label><label>Policyholder ID<input name="policyholder_id" required placeholder="UUID"></label><label>Claim amount<input name="claim_amount" type="number" min="0" step=".01" required placeholder="0.00"></label><label>Incident date<input name="incident_date" type="date" required></label></div><label>Description<textarea name="description" required rows="3"></textarea></label><button class="primary">Submit workflow</button></form></section>${workflowCard()}`);
  if (active === "records") return shell(`<div class="page-head"><div><p class="eyebrow">Lookup</p><h1>Policy & claim records</h1><p class="muted">Read-only views are scoped to the selected policyholder.</p></div></div><section class="card lookup"><form id="lookup-form"><label>Policyholder ID<input name="holder" required placeholder="UUID"></label><button class="primary">Load records</button></form></section><div id="records-output"></div>`);
  if (active === "reconciliation") return shell(`<div class="page-head"><div><p class="eyebrow">Controls</p><h1>Audit & reconciliation</h1><p class="muted">Review failed steps, retry history, and control exceptions.</p></div></div>${workflow ? workflowCard() : `<section class="empty card"><span class="empty-icon">◈</span><h2>No workflow selected</h2><p>Open a workflow from the overview or submit one to inspect its audit trail.</p><button class="secondary" data-nav="workflows">Submit a workflow</button></section>`}`);
  return shell(`<div class="page-head"><div><p class="eyebrow">Today · ${new Date().toLocaleDateString()}</p><h1>Good morning, operator</h1><p class="muted">A focused view of work requiring attention.</p></div><button class="secondary" data-nav="workflows">+ New workflow</button></div><div class="stats"><div class="stat"><span>Open workflows</span><strong>${workflow ? 1 : "—"}</strong><small>Live from orchestrator</small></div><div class="stat"><span>Reconciliation</span><strong class="${workflow?.state === "reconciliation_required" ? "danger" : ""}">${workflow?.state === "reconciliation_required" ? 1 : 0}</strong><small>Needs operator review</small></div><div class="stat"><span>Retry attempts</span><strong>${workflow?.retry_count ?? "—"}</strong><small>Current selection</small></div></div><section class="card hero-card"><div><p class="eyebrow">Control center</p><h2>Keep claims moving safely.</h2><p>Submit a workflow, trace downstream steps, and retry recoverable failures without leaving the operations console.</p></div><div class="hero-art">◒<span>↗</span></div></section>${workflowCard()}`);
}
function workflowCard() {
  if (!workflow) return "";
  const canRetry = workflow.state === "failed" || workflow.state === "reconciliation_required";
  return `<section class="card workflow-card"><div class="section-head"><div><p class="eyebrow">Selected workflow</p><h2>${esc(workflow.id)}</h2></div><div>${badge(workflow.state)} ${workflow.retry_count ? `<span class="retry">↻ ${workflow.retry_count} retries</span>` : ""}</div></div><div class="timeline">${workflow.steps.map(s => `<div class="step"><span class="step-icon ${esc(s.state)}">${s.state === "succeeded" ? "✓" : s.state === "failed" ? "!" : "·"}</span><div><strong>${esc(s.name)}</strong><small>${esc(s.error_category ?? s.state)} ${s.completed_at ? `· ${new Date(s.completed_at).toLocaleString()}` : ""}</small></div></div>`).join("")}</div>${workflow.failure_category ? `<div class="alert">⚠ ${esc(workflow.failure_category)} — review the failed step before retrying.</div>` : ""}${canRetry ? `<button id="retry" class="secondary">↻ Retry workflow</button>` : ""}</section>`;
}
async function run<T>(action: () => Promise<T>, success: (value: T) => void) { message = ""; try { success(await action()); } catch (error) { message = error instanceof ApiError ? `${error.message}${error.requestId ? ` · Request ${error.requestId}` : ""}` : "Unable to complete request."; render(); } }
document.addEventListener("submit", event => {
  const form = event.target as HTMLFormElement; event.preventDefault(); const data = Object.fromEntries(new FormData(form));
  if (form.id === "workflow-form") run(() => client.submitWorkflow({ ...data, claim_amount: Number(data.claim_amount) }), value => { workflow = value; message = "Workflow submitted successfully."; render(); });
  if (form.id === "lookup-form") run(async () => ({ policies: await client.listPolicies(String(data.holder)), claims: await client.listClaims(String(data.holder)) }), value => { const out = document.querySelector("#records-output"); if (out) out.innerHTML = `<div class="record-grid"><section class="card"><div class="section-head"><h2>Policies</h2><span class="count">${value.policies.length}</span></div>${value.policies.map((p: Policy) => `<article class="record"><div><strong>${esc(p.coverage_type)}</strong><small>${esc(p.id)}</small></div>${badge(p.status)}<b>$${esc(p.premium_amount ?? "—")}</b></article>`).join("") || "<p class='muted'>No policies found.</p>"}</section><section class="card"><div class="section-head"><h2>Claims</h2><span class="count">${value.claims.length}</span></div>${value.claims.map((c: Claim) => `<article class="record"><div><strong>${esc(c.description)}</strong><small>${esc(c.id)}</small></div>${badge(c.status)}<b>$${esc(c.claim_amount)}</b></article>`).join("") || "<p class='muted'>No claims found.</p>"}</section></div>`; });
});
document.addEventListener("click", event => { const target = event.target as HTMLElement; if (target.id === "menu") document.querySelector("nav")?.classList.toggle("open"); if (target.id === "retry" && workflow) run(() => client.retryWorkflow(workflow!.id), value => { workflow = value; message = "Workflow retry requested."; render(); }); if (target.dataset.nav) { active = target.dataset.nav; render(); } });
render();
